---
- name: Update system
  apt:
    update_cache: true
    upgrade: safe

- name: Install utilities
  apt:
    name:
      - git
      - curl
      - ufw
      - fail2ban
      - htop
    state: present

- name: Configure firewall
  when: enable_firewall
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - 22
    - "{{ http_port }}"
    - "{{ backend_port }}"

