---
- name: Install Docker + Compose plugin
  apt:
    name:
      - docker.io
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Ensure Docker service running
  service:
    name: docker
    state: started
    enabled: true

